name: Manual Station Update

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pillow

      - name: keep only last 03 json files
        run: |
          ls -t status_caz_*.json | tail -n +4 | xargs -r rm --

      - name: Run script
        run: python get_mausam_rdr_img_status.py

      - name: Copy latest file
        run: |
          LATEST=$(ls -t status_caz_*.json | head -n 1)
          cp "$LATEST" status_all_latest.json

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add status_caz_*.json status_caz_latest.json
          git commit -m "Manual update" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
      
      


